### ISSUE TITLE
Enable debugging pareview.sh style

### ISSUE THREAD

**Issue by ikit-claw** [vijaycs85/drupal-quality-checker#2]
First of all, this is awesome thanks for the project.

Would it be possible to extend this to make it pick up the following?
Coder Sniffer
DrupalPractice
Codespell
  
These do not seem to be picked up by the quality checker.

**Comment by vijaycs85** [comment]
Sure, we just need to add additional checks. I think code sniffer is already set. PRs are welcome 👍

**Comment by q0rban** [comment]
To add DrupalPractice to Codesniffer, in grumphp.yml:

```yml
parameters:
  tasks:
    phpcs:
      standard: Drupal,DrupalPractice
```
